name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - id: get-project
        name: Get project name
        run: |
          if [ ! -f "project-to-build" ]; then
            echo "Error: project-to-build file not found!"
            exit 1
          fi
          PROJECT=$(cat project-to-build)
          echo "PROJECT=$PROJECT" >> $GITHUB_OUTPUT

      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project

      - name: Build the app
        working-directory: ./project
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-build-apk
          path: |
            **/*.apk
